### ISSUE TITLE
Enemy Churches can not be destroyed

### ISSUE THREAD

**Issue by Jeeppler** [0ADMods/millenniumad#24]
Issue: Enemy Churches can not be destroyed

Expected behavior: Churches can be destroyed

Version: Millennium A.D. from ModDB + 0 A.D. 21

Fraction: Carolingian

**Comment by StanleySweet** [comment]
What do you mean by "Enemy Churches can not be destroyed" Is there an issue when destroying them,  or does the health not reach 0 ?

**Comment by Jeeppler** [comment]
The visible is I cannot destroy a church if it is a construction field and a finished church of the Carolingian fraction. Internally, that maybe has something to do with the church not reaching 0 health. However, I did not debug or investigate the issue in more detail. So, basically I cannot say that for sure.

**Comment by AlexanderVzla** [comment]
There was a bug with anglo civ center and temple because of a wrong rubble template but those were fixed but he mention carolingian faction:

![image](https://user-images.githubusercontent.com/29136612/40945130-58b2c364-6825-11e8-8ca4-9e2338b14c52.png)

![image](https://user-images.githubusercontent.com/29136612/40945138-610de8e0-6825-11e8-82a4-d03b9397a298.png)

**Comment by StanleySweet** [comment]
I just checked for rubble in the folders and couldn't find anything that could cause issues. Everything has been fixed, so I'm closing this. :)
